version: 0.0
os: linux
files:
  - source: ./
    destination: /home/b9b/www
hooks:
  ApplicationStop:
    - location: codedeploy/application_stop.sh
      runas: root
  BeforeInstall:
    - location: codedeploy/before_install.sh
      runas: root
      # Allow plenty of time to compile all the things.
      # https://xkcd.com/303/
      timeout: 6800
  ApplicationStart:
    - location: codedeploy/application_start.sh
      runas: root
      timeout: 3000
  ValidateService:
    - location: codedeploy/validate_service.sh
      runas: root
