version: 0.0
os: linux
files:
  - source: /.
    destination: /var/www/html/
language: ruby
rvm:
  - 2.4.1
  - jruby-head
hooks:
  BeforeInstall:
    - gem install bundler
    - gem update bundler
    - gem install sinatra
  ApplicationStop:
    - location: app.rb
      timeout: 300
      runas: root
  ApplicationStart:
    - location: app.rb
      timeout: 300
      runas: root


