#!/bin/bash
sudo yum update
sudo yum install ruby
sudo yum install wget

 sudo yum install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties libffi-dev
 cd ~
 git clone git://github.com/sstephenson/rbenv.git .rbenv
 echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> .bashrc
 echo 'eval "$(rbenv init -)"; fi' >> .bashrc
 exec $SHELL
 git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
 echo 'export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"' >> .bashrc
 exec $SHELL
git clone https://github.com/sstephenson/rbenv-gem-rehash.git .rbenv/plugins/rbenv-gem-rehash

gem install bundler
gem update --system
bundle install
 rbenv install 2.2.3
rbenv global 2.2.3
 ruby -v
 
gem install bundler

gem install sinatra

